apiVersion: apps/v1
kind: Deployment
metadata: { name: suggestion-service }
spec:
  replicas: 1
  selector: { matchLabels: { app: sugg } }
  template:
    metadata: { labels: { app: sugg } }
    spec:
      containers:
        - name: suggestion
          image: suggestion-service:latest
          imagePullPolicy: Never
          env:
            - { name: SPRING_DATASOURCE_URL, value: "jdbc:postgresql://postgres:5432/rca" }
            - { name: SPRING_DATASOURCE_USERNAME, value: "rcauser" }
            - { name: SPRING_DATASOURCE_PASSWORD, value: "rcapass" }
          ports: [{ containerPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata: { name: suggestion-service }
spec:
  selector: { app: sugg }
  ports: [{ port: 8080, targetPort: 8080 }]
