name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build Java services
        run: |
          for svc in rca-service log-service suggestion-service; do
            (cd $svc && mvn -q -DskipTests package)
          done
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build frontend
        run: |
          cd frontend && npm ci && npm run build
      - name: Python lint
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff ml-service
